name: Deploy to Github Pages
on:
  push:
#    branches:
#      - main
jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Install packages
        run: npm install
      - name: Set Creds
        run: git config user.name "deployer" && git config user.email "deploy@mail.com"
      - name: set update time
        run: >
          update=$(date +"%Y.%m.%d %H:%M");
          sed -e 's|#GeradeEben#|'$update'|' -i src/App.vue
      - name: Deploy
        run: npm run deploy