name: performance tests
on: [ pull_request ]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npm install
      - run: npm run build
      - run: npm run serve &
      - run: sleep 20
      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@v7.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          urls: 'https://lkwg82.github.io/covid19.barnim/,http://localhost:5000'
