name: performance tests
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@v7.1.0
        with:
          gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          urls: 'https://lkwg82.github.io/covid19.barnim/'
